[package]
name = "rp235x"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
capability = { path = "../../capability" }
debugger = { path = "../../debugger" }
runtime-core = { path = "../../runtime/runtime-core" }

embassy-rp = { workspace = true }
embassy-net = { workspace = true, features = ["dhcpv4-hostname", "proto-ipv6", "slaac"] }
embassy-executor = { workspace = true }
embassy-sync = { workspace = true }
embassy-time = { workspace = true }
embassy-boot-rp = { workspace = true }

cyw43 = { workspace = true, features = ["defmt", "firmware-logs", "bluetooth"] }
cyw43-pio = { workspace = true }

static_cell = { workspace = true }
heapless = { workspace = true }
log = { workspace = true }
embedded-io-async = { workspace = true }
embedded-storage = { workspace = true }
serde = { workspace = true }
serde-json-core = { workspace = true }
sha2 = { workspace = true }
bt-hci = "0.9.0"

reqwless = {
    git = "https://github.com/drogue-iot/reqwless",
    rev = "68f703dfc16e6f7f964b7238c922c0d433118872",
    features = ["defmt", "alloc"]
}
