[package]
name = "rp235x"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
function = { path = "../../function" }

embassy-rp = { workspace = true }
embassy-net = { workspace = true, features = ["dhcpv4-hostname"] }
embassy-executor = { workspace = true }

cyw43 = { workspace = true }
cyw43-pio = { workspace = true }

static_cell = { workspace = true }
heapless = { workspace = true }
embedded-io-async = { workspace = true }
